config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'main#index'
  get 'contact', to: 'static_pages#contact'
  resources :courses, only: [:index] do
    resources :lessons, only: [:index,:show]
  end
  devise_for :users, path_names: { sign_in: 'login',
                                   sign_out: 'logout',
                                   password: 'secret',
                                   sign_up: 'registration' }, controllers: {
                                     registrations: 'users/registrations'
                                   }
  scope :admin do
    devise_for :admins, controllers: { sessions: 'admin/admins/sessions' }
  end
  namespace :admin do
    root to: 'main#index'
    get 'main/index'
    resources :teachers, except: :show
    resources :disciplines, except: :show
    resources :admins, except: :show

    resources :courses, except: :show do
      resources :lessons, except: :show
    end

    resources :lessons, only: [] do
      post :sort, on: :collection
    end

    namespace :api do
      namespace :lessons do
        resource :mass_update, only: :create
      end

      resources :lessons, only: [] do
        resource :tinymce_images, only: :create, owner: 'lesson'
      end
      resources :courses, only: [] do
        resource :tinymce_images, only: :create, owner: 'course'
      end
    end
  end
end

app/models/lesson.rb
# frozen_string_literal: true

class Lesson < ApplicationRecord
  belongs_to :course
  belongs_to :section
  has_many :tinymce_images, as: :owner

  validates :name, presence: true
  validates :description, presence: true

  acts_as_list

  def self.reorder(order_params)
    order_params.each_with_index do |id, index|
      # Lesson.find(id).update!(position: index + 1)
      Lesson.find(id).set_list_position(index, true)
    end
  end
end

app/controllers/admin/api/lessons/mass_updates_controller.rb
# frozen_string_literal: true

class Admin::Api::Lessons::MassUpdatesController < Admin::Api::BaseController
  def create
    ::Lessons::MassUpdate.create!(lessons_params)

    head :no_content
  end

  private

  def lessons_params
    params.permit(lessons: %i[id position section_id])[:lessons].values
  end
end

app/controllers/admin/lessons_controller.rb
# frozen_string_literal: true

class Admin::LessonsController < Admin::BaseController
  skip_before_action :set_active_main_menu_item, only: :sort

  before_action :set_course, except: :sort
  before_action :set_lesson, only: %i[edit update destroy]

  def index
    @lessons = @course.lessons.order(:position).page(params[:page]).per(5)
  end

  def new
    add_breadcrumb 'Новое Занятие', [:new, :admin, @course, :lesson]
    @lesson = @course.lessons.build
    @lesson.id = 1
  end

  def create
    @lesson = @course.lessons.build(lesson_params)
    if @lesson.save
      redirect_to [:admin, @course, :lessons], notice: 'Занятие успешно создано'
    else
      flash.now[:alert] = 'Не удалось создать занятие'
      add_breadcrumb 'Новое Занятие', [:new, :admin, @course, :lesson]
      render :new
    end
  end

  def edit
    add_breadcrumb "Изменить #{@lesson.name}", [:edit, :admin, @course, :lesson]
  end

  def update
    if @lesson.update(lesson_params)
      redirect_to [:admin, @course, :lessons], notice: 'Занятие успешно изменено'
    else
      flash.now[:alert] = 'Не удалось изменить занятие'
      add_breadcrumb "Изменить #{@lesson.name}", [:edit, :admin, @course, :lesson]
      render :edit
    end
  end

  def destroy
    if @lesson.destroy
      redirect_to [:admin, @course, :lessons], notice: 'Занятие успешно удалено'
    else
      redirect_to [:admin, @course, :lessons], alert: 'Не удалось удалить занятие'
    end
  end

  def sort
    Lesson.reorder(params[:lesson])
    head :no_content
  end

  private

  def lesson_params
    params.require(:lesson).permit(:name, :description, :section_id)
  end

  def set_course
    @course = Course.find(params[:course_id])
    add_breadcrumb 'Курсы', :admin_courses_path
    add_breadcrumb @course.name, [:admin, @course, :lessons]
  end

  def set_lesson
    @lesson = Lesson.find(params[:id])
  end

  def set_active_main_menu_item
    @main_menu[:courses][:active] = true
  end
end

app/controllers/lessons_controller.rb
# frozen_string_literal: true

class LessonsController < ApplicationController
  before_action :lesson, :sections

  private

  def sections
    @sections = course.sections.order(:position)
  end

  def course
    @course = Course.find(params[:course_id])
  end

  def lesson
    @lesson = course.lessons.find(params[:id]) if params[:id].present?
  end
end

app/views/lessons/index.html.slim
/! start banner Area
section#home.banner-area.relative.about-banner
  .overlay.overlay-bg
  .container
    .row.d-flex.align-items-center.justify-content-center
      .about-content.col-lg-12
        h1.text-white
          = @course.name
        p.text-white.link-nav
          = link_to 'Home', '/'
          span.lnr.lnr-arrow-right
          = link_to 'Courses', courses_path
          span.lnr.lnr-arrow-right
          = link_to @course.name, course_lessons_path(@course)
/! End banner Area
/! Start course-details Area
section.course-details-area.pt-25
  .container
    .row
      .col-lg-8.left-contents
        .main-image
          = image_tag @course.tinymce_images.take.file.url, title: "", class: "img-fluid"
        #horizontalTab.jq-tab-wrapper
          .jq-tab-menu
            .jq-tab-title.active data-tab="1"  Lessons
            .jq-tab-title data-tab="2"  Description
            .jq-tab-title data-tab="4"  Comments
            .jq-tab-title data-tab="5"  Reviews
          .jq-tab-content-wrapper
            .jq-tab-content.active data-tab="1"
              ul.section-list
                - @sections.each do |section|
                  li
                    p.section-box
                      = section.name
                    ul.course-list
                      - section.lessons.each do |lesson|
                        li.justify-content-between.d-flex
                          p = lesson.name
                          / a.primary-btn.text-uppercase href="#"  View Details
                          = link_to "View Details", course_lesson_path(@course, lesson), class: "primary-btn text-uppercase"
            .jq-tab-content data-tab="2"
              | Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum.
              br/
              br/
              | Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum.
            .jq-tab-content.comment-wrap data-tab="4"
              .comments-area
                h4 05 Comments
                .comment-list
                  .single-comment.justify-content-between.d-flex
                    .user.justify-content-between.d-flex
                      .thumb
                        = image_tag "blog/c1.jpg", alt: "",title: ""
                      .desc
                        h5
                          a href="#"  Emilly Blunt
                        p.date December 4, 2017 at 3:12 pm
                        p.comment
                          | Never say goodbye till the end comes!
                    .reply-btn
                      a.btn-reply.text-uppercase href=""  reply
                .comment-list.left-padding
                  .single-comment.justify-content-between.d-flex
                    .user.justify-content-between.d-flex
                      .thumb
                        = image_tag "blog/c2.jpg", alt: "",title: ""
                      .desc
                        h5
                          a href="#"  Elsie Cunningham
                        p.date December 4, 2017 at 3:12 pm
                        p.comment
                          | Never say goodbye till the end comes!
                    .reply-btn
                      a.btn-reply.text-uppercase href=""  reply
                .comment-list
                  .single-comment.justify-content-between.d-flex
                    .user.justify-content-between.d-flex
                      .thumb
                        = image_tag "blog/c4.jpg", alt: "",title: ""
                      .desc
                        h5
                          a href="#"  Maria Luna
                        p.date December 4, 2017 at 3:12 pm
                        p.comment
                          | Never say goodbye till the end comes!
                    .reply-btn
                      a.btn-reply.text-uppercase href=""  reply
              .comment-form
                h4 Leave a Comment
                form
                  .form-group.form-inline
                    .form-group.col-lg-6.col-md-12.name
                      input#name.form-control onblur=("this.placeholder = 'Enter Name'") onfocus=("this.placeholder = ''") placeholder=("Enter Name") type="text" /
                    .form-group.col-lg-6.col-md-12.email
                      input#email.form-control onblur=("this.placeholder = 'Enter email address'") onfocus=("this.placeholder = ''") placeholder=("Enter email address") type="email" /
                  .form-group
                    input#subject.form-control onblur=("this.placeholder = 'Subject'") onfocus=("this.placeholder = ''") placeholder="Subject" type="text" /
                  .form-group
                    textarea.form-control.mb-10 name="message" onblur=("this.placeholder = 'Messege'") onfocus=("this.placeholder = ''") placeholder="Messege" required="" rows="5"
                  a.mt-40.text-uppercase.genric-btn.primary.text-center href="#"  Post Comment
            .jq-tab-content data-tab="5"
              .review-top.row.pt-40
                .col-lg-3
                  .avg-review
                    | Average
                    br/
                    span 5.0
                    br/
                    | (3 Ratings)
                .col-lg-9
                  h4.mb-20 Provide Your Rating
                  .d-flex.flex-row.reviews
                    span Quality
                    .star
                      i.fa.fa-star.checked
                      i.fa.fa-star.checked
                      i.fa.fa-star.checked
                      i.fa.fa-star
                      i.fa.fa-star
                    span Outstanding
                  .d-flex.flex-row.reviews
                    span Puncuality
                    .star
                      i.fa.fa-star.checked
                      i.fa.fa-star.checked
                      i.fa.fa-star.checked
                      i.fa.fa-star
                      i.fa.fa-star
                    span Outstanding
                  .d-flex.flex-row.reviews
                    span Quality
                    .star
                      i.fa.fa-star.checked
                      i.fa.fa-star.checked
                      i.fa.fa-star.checked
                      i.fa.fa-star
                      i.fa.fa-star
                    span Outstanding
              .feedeback
                h4.pb-20 Your Feedback
                textarea.form-control cols="10" name="feedback" rows="10"
                a.mt-20.primary-btn.text-right.text-uppercase href="#"  Submit
              .comments-area.mb-30
                .comment-list
                  .single-comment.single-reviews.justify-content-between.d-flex
                    .user.justify-content-between.d-flex
                      .thumb
                        = image_tag "blog/c1.jpg", alt: "",title: ""
                      .desc
                        h5
                          a href="#"  Emilly Blunt
                          .star
                            span.fa.fa-star.checked
                            span.fa.fa-star.checked
                            span.fa.fa-star.checked
                            span.fa.fa-star
                            span.fa.fa-star
                        p.comment
                          | Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum ut sed, dolorum asperiores perspiciatis provident, odit maxime doloremque aliquam.
                .comment-list
                  .single-comment.single-reviews.justify-content-between.d-flex
                    .user.justify-content-between.d-flex
                      .thumb
                        = image_tag "blog/c2.jpg", alt: "",title: ""
                      .desc
                        h5
                          a href="#"  Elsie Cunningham
                          .star
                            span.fa.fa-star.checked
                            span.fa.fa-star.checked
                            span.fa.fa-star.checked
                            span.fa.fa-star
                            span.fa.fa-star
                        p.comment
                          | Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum ut sed, dolorum asperiores perspiciatis provident, odit maxime doloremque aliquam.
                .comment-list
                  .single-comment.single-reviews.justify-content-between.d-flex
                    .user.justify-content-between.d-flex
                      .thumb
                        = image_tag "blog/c3.jpg", alt: "",title: ""
                      .desc
                        h5
                          a href="#"  Maria Luna
                          .star
                            span.fa.fa-star.checked
                            span.fa.fa-star.checked
                            span.fa.fa-star.checked
                            span.fa.fa-star
                            span.fa.fa-star
                        p.comment
                          | Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum ut sed, dolorum asperiores perspiciatis provident, odit maxime doloremque aliquam.
                .comment-list
                  .single-comment.single-reviews.justify-content-between.d-flex
                    .user.justify-content-between.d-flex
                      .thumb
                        = image_tag "blog/c4.jpg", alt: "",title: ""
                      .desc
                        h5
                          a href="#"  Maria Luna
                          .star
                            span.fa.fa-star.checked
                            span.fa.fa-star.checked
                            span.fa.fa-star.checked
                            span.fa.fa-star
                            span.fa.fa-star
                        p.comment
                          | Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum ut sed, dolorum asperiores perspiciatis provident, odit maxime doloremque aliquam.
      .col-lg-4.right-contents
        ul
          li
            a.justify-content-between.d-flex href="#"
              p Trainer’s Name
              span.or = @course.teacher.full_name
          li
            a.justify-content-between.d-flex href="#"
              p Duration
              span 8 Hours
          li
            a.justify-content-between.d-flex href="#"
              p Start
              span 16/11/2019
          li
            a.justify-content-between.d-flex href="#"
              p Progress
              span 0/8
        a.primary-btn.text-uppercase href="#"  Enroll the course
        /! End course-details Area

app/views/lessons/show.html.slim
/! start banner Area
section#home.banner-area.relative.about-banner
  .overlay.overlay-bg
  .container
    .row.d-flex.align-items-center.justify-content-center
      .about-content.col-lg-12
        h1.text-white
          = @course.name
        p.text-white.link-nav
          = link_to 'Home', '/'
          span.lnr.lnr-arrow-right
          = link_to 'Courses', courses_path
          span.lnr.lnr-arrow-right
          = link_to @course.name, course_lessons_path(@course)
          span.lnr.lnr-arrow-right
          = link_to @lesson.name, course_lesson_path(@course, @lesson)
/! End banner Area
/! Start course-details Area
section.course-details-area.pt-25
  .container
    .row
      .col-lg-8.left-contents
        h1 = @lesson.name
        .main-image
        #horizontalTab.jq-tab-wrapper
          .jq-tab-menu
            .jq-tab-title.active data-tab="1"  Description
            .jq-tab-title data-tab="2"  Video
            .jq-tab-title data-tab="3"  Conspect
            .jq-tab-title data-tab="4"  Task
          .jq-tab-content-wrapper
            .jq-tab-content.active data-tab="1"
              = @lesson.description.html_safe
            .jq-tab-content data-tab="2"
            .jq-tab-content data-tab="3"
            .jq-tab-content data-tab="4"

      .col-lg-4.right-contents
        ul.section-list
          - @sections.each do |section|
            li
              p.section-box
                = section.name
              ul.course-list
                - section.lessons.each do |lesson|
                  li.justify-content-between.d-flex
                    p = lesson.name
                    / a.primary-btn.text-uppercase href="#"  View Details
                    = link_to "View Details", course_lesson_path(@course, lesson)
/! End course-details Area