config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'main#index'
  get 'contact', to: 'static_pages#contact'
  resources :courses, only: [:index] do
    resources :lessons, only: [:index,:show]
  end
  devise_for :users, path_names: { sign_in: 'login',
                                   sign_out: 'logout',
                                   password: 'secret',
                                   sign_up: 'registration' }, controllers: {
                                     registrations: 'users/registrations'
                                   }
  scope :admin do
    devise_for :admins, controllers: { sessions: 'admin/admins/sessions' }
  end
  namespace :admin do
    root to: 'main#index'
    get 'main/index'
    resources :teachers, except: :show
    resources :disciplines, except: :show
    resources :admins, except: :show

    resources :courses, except: :show do
      resources :lessons, except: :show
    end

    resources :lessons, only: [] do
      post :sort, on: :collection
    end

    namespace :api do
      namespace :lessons do
        resource :mass_update, only: :create
      end

      resources :lessons, only: [] do
        resource :tinymce_images, only: :create, owner: 'lesson'
      end
      resources :courses, only: [] do
        resource :tinymce_images, only: :create, owner: 'course'
      end
    end
  end
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :registerable, :recoverable, :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
# frozen_string_literal: true

class Course < ApplicationRecord
  belongs_to :teacher
  has_many :lessons
  has_many :tinymce_images, as: :owner

  has_many :course_disciplines, dependent: :delete_all
  has_many :disciplines, through: :course_disciplines
  has_many :sections, dependent: :delete_all

  validates :name, presence: true
  validates :description, presence: true
  validates :disciplines, presence: true

  accepts_nested_attributes_for :sections, reject_if: :all_blank, allow_destroy: true
end

app/models/course_discipline.rb
# frozen_string_literal: true

class CourseDiscipline < ApplicationRecord
  belongs_to :discipline
  belongs_to :course
end

app/models/discipline.rb
# frozen_string_literal: true

class Discipline < ApplicationRecord
  has_many :course_disciplines
  has_many :courses, through: :course_disciplines

  validates :name, presence: true
end

app/models/lesson.rb
# frozen_string_literal: true

class Lesson < ApplicationRecord
  belongs_to :course
  belongs_to :section
  has_many :tinymce_images, as: :owner

  validates :name, presence: true
  validates :description, presence: true

  acts_as_list

  def self.reorder(order_params)
    order_params.each_with_index do |id, index|
      # Lesson.find(id).update!(position: index + 1)
      Lesson.find(id).set_list_position(index, true)
    end
  end
end

app/models/section.rb
# frozen_string_literal: true

class Section < ApplicationRecord
  belongs_to :course
  has_many :lessons, dependent: :delete_all

  validates :name, presence: true
  validates :description, presence: true
  validates :course_id, presence: true

  acts_as_list
end

app/models/teacher.rb
# frozen_string_literal: true

class Teacher < ApplicationRecord
  has_many :courses

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description, presence: true

  def full_name
    [first_name, last_name].join(' ')
  end
end

app/models/tinymce_image.rb
# frozen_string_literal: true

class TinymceImage < ApplicationRecord
  belongs_to :owner, polymorphic: true
  mount_uploader :file, TinymceImageUploader
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, :last_name, presence: true
end

app/controllers/admin/admins_controller.rb
# frozen_string_literal: true

class Admin::AdminsController < Admin::BaseController
  add_breadcrumb 'Админы', :admin_admins_path
  before_action :set_admin, only: %i[edit update destroy]

  def index
    @admins = Admin.order(id: :desc).page(params[:page]).per(5)
  end

  def new
    add_breadcrumb 'Новый Админ', new_admin_admin_path
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(admin_params)
    if @admin.save
      redirect_to admin_admins_path, notice: 'Админ успешно создан'
    else
      flash.now[:alert] = 'Не удалось создать админа'
      add_breadcrumb 'Новый Админ', new_admin_admin_path
      render :new
    end
  end

  def edit
    add_breadcrumb "Изменить #{@admin.first_name} #{@admin.last_name}", [:edit, :admin, @admin]
  end

  def update
    if @admin.update(admin_params)
      redirect_to admin_admins_path, notice: 'Админ успешно изменен'
    else
      flash.now[:alert] = 'Не удалось изменить админа'
      add_breadcrumb "Изменить #{@admin.first_name} #{@admin.last_name}", [:edit, :admin, @admin]
      render :edit
    end
  end

  def destroy
    if @admin.destroy
      redirect_to admin_admins_path, notice: 'Админ успешно удален'
    else
      redirect_to admin_admins_path, alert: 'Не удалось удалить админа'
    end
  end

  private

  def admin_params
    params.require(:admin).permit(:email, :first_name, :last_name, :password)
  end

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def set_active_main_menu_item
    @main_menu[:admins][:active] = true
  end
end

app/controllers/admin/base_controller.rb
# frozen_string_literal: true

class Admin::BaseController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!

  before_action :set_main_menu, except: :destroy
  before_action :set_active_main_menu_item, except: :destroy

  private

  def set_main_menu
    @main_menu = {
      courses: { name: 'Курсы', path: admin_courses_path },
      teachers: { name: 'Преподаватели', path: admin_teachers_path },
      disciplines: { name: 'Дисциплины', path: admin_disciplines_path },
      admins: { name: 'Админы', path: admin_admins_path }
    }
  end
end

app/controllers/admin/main_controller.rb
# frozen_string_literal: true

class Admin::MainController < Admin::BaseController
  skip_before_action :set_active_main_menu_item
  def index
    redirect_to admin_courses_path
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
# frozen_string_literal: true

class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end
end

app/controllers/lessons_controller.rb
# frozen_string_literal: true

class LessonsController < ApplicationController
  before_action :lesson, :sections

  private

  def sections
    @sections = course.sections.order(:position)
  end

  def course
    @course = Course.find(params[:course_id])
  end

  def lesson
    @lesson = course.lessons.find(params[:id]) if params[:id].present?
  end
end

app/controllers/main_controller.rb
# frozen_string_literal: true

class MainController < ApplicationController
  def index
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def contact
  end
end

app/helpers/admin_helper.rb
# frozen_string_literal: true

module AdminHelper
  def render_flash
    # %w[notice alert]
    #     .select { |type| flash_block(type) }
    #     .map { |type| flash_block(type) }
    #     .join.html_safe

    return unless [:notice].present?

    %w[notice]
      .select { |type| flash_block(type) }
      .map { |type| flash_block(type) }
      .join.html_safe

    return unless flash[:alert].present?

    %w[alert]
      .select { |type| flash_block(type) }
      .map { |type| flash_block(type) }
      .join.html_safe
  end

  private

  def flash_block(type)
    flash_classes = { notice: 'alert alert-success', alert: 'alert alert-danger' }
    content_tag(:div, class: flash_classes[type.to_sym]) do
      content_tag('button', 'x', class: 'close clear', 'data-dismiss' => 'alert') + flash[type.to_sym]
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/admin/admins/_admin.html.slim
tr
  td
    .btn-group-vertical role="group"
      = link_to [:edit, :admin, admin], class: 'btn btn-primary btn-sm' do
        span.glyphicon.glyphicon-pencil aria-hidden="true"
      = link_to [:admin, admin], class: 'btn btn-danger btn-sm', method: :delete,data: {confirm: 'Действительно хотите удалить?' } do
        span.glyphicon.glyphicon-trash aria-hidden="true"
  td= admin.first_name
  td= admin.last_name
  td= admin.email

app/views/admin/admins/_form.html.slim
= simple_form_for [:admin, @admin], wrapper: :horizontal_form, html: { class: 'form-horizontal'} do |f|
  = f.input :email
  = f.input :first_name
  = f.input :last_name
  = f.input :password
  .row
    .col-md-4.col-md-offset-3.button_box
      = f.button :submit, 'Сохранить', class: 'btn btn-primary'
      = link_to 'Отменить', admin_admins_path, class: 'btn btn-default'

app/views/admin/admins/edit.html.slim
h3 Редактирование Админа
hr
= render 'form'

app/views/admin/admins/index.html.slim
h3 Админы
= link_to 'Добавить админа',new_admin_admin_path, class: 'btn btn-success pull-right'
table.table.table-striped
  thead
    tr
      th Название
  tbody
    = render @admins
= paginate @admins, theme:  'twitter-bootstrap-3'

app/views/admin/admins/new.html.slim
h3 Новый Админ
hr
= render 'form'

app/views/admin/shared/_main_menu.html.slim
nav.navbar.navbar-default
  .container-fluid
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'OnSchool', admin_root_path, class: 'navbar-brand'
    - if current_admin
      /! Collect the nav links, forms, and other content for toggling
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        ul.nav.navbar-nav
          - @main_menu.each do |item, options|
            li class=(options[:active] ? 'active' : '')
              = link_to options[:path] do
                = options[:name]
                - if options[:active]
                  span.sr-only (current)
        ul.nav.navbar-nav.navbar-right
          li.dropdown
            a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
              | #{current_admin.first_name} #{current_admin.last_name}
              span.caret
            ul.dropdown-menu
              li
                a href="#"  Action
              li.divider role="separator"
              li
                = link_to 'Выйти', destroy_admin_session_path, method: :delete
    /! /.navbar-collapse
    /! /.container-fluid

app/views/layouts/admin.html.slim
doctype html
html
  head
    title
      | OnSchool
    = csrf_meta_tags
    = stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'admin', 'data-turbolinks-track': 'reload'
  body
    =render 'admin/shared/main_menu'
    .container
      - if current_admin
        .row
          .col-md-12
            / = render_breadcrumbs :separator => ' / '
            ol.breadcrumb
              = render_breadcrumbs tag: :li, separator: ""
      .row
        .col-md-12
          = render_flash
      .row
        .col-md-12
          = yield

app/views/layouts/application.html.slim
doctype html
html.no-js lang="zxx"
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    /! Mobile Specific Meta
    meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport" /
    title OnSchool
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    /! Favicon
    / link href="img/fav.png" rel=("shortcut icon") /
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header#header
      = render partial: 'shared/header'
    /! #header
    = yield
    /! start footer Area
    = render partial: 'shared/footer'
    /! End footer Area
    script crossorigin="anonymous" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"

app/views/shared/_footer.html.slim
footer.footer-area.section-gap
  .container
    .row
      .col-lg-2.col-md-6.col-sm-6
        .single-footer-widget
          h4 Top Products
          ul
            li
              a href="#"  Managed Website
            li
              a href="#"  Manage Reputation
            li
              a href="#"  Power Tools
            li
              a href="#"  Marketing Service
      .col-lg-2.col-md-6.col-sm-6
        .single-footer-widget
          h4 Quick links
          ul
            li
              a href="#"  Jobs
            li
              a href="#"  Brand Assets
            li
              a href="#"  Investor Relations
            li
              a href="#"  Terms of Service
      .col-lg-2.col-md-6.col-sm-6
        .single-footer-widget
          h4 Features
          ul
            li
              a href="#"  Jobs
            li
              a href="#"  Brand Assets
            li
              a href="#"  Investor Relations
            li
              a href="#"  Terms of Service
      .col-lg-2.col-md-6.col-sm-6
        .single-footer-widget
          h4 Resources
          ul
            li
              a href="#"  Guides
            li
              a href="#"  Research
            li
              a href="#"  Experts
            li
              a href="#"  Agencies
      .col-lg-4.col-md-6.col-sm-6
        .single-footer-widget
          h4 Newsletter
          p Stay update with our latest
          #mc_embed_signup
            form action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&id=92a4423d01" method="get" target="_blank"
              .input-group
                input.form-control name="EMAIL" onblur=("this.placeholder = 'Enter Email Address '") onfocus=("this.placeholder = ''") placeholder=("Enter Email Address") required="" type="text" /
                .input-group-btn
                  button.btn.btn-default type="submit"
                    span.lnr.lnr-arrow-right
                .info
    .footer-bottom.row.align-items-center.justify-content-between
      p.footer-text.m-0.col-lg-6.col-md-12
        /! Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0.
        | Copyright ©
        javascript:
            |
            document.write(new Date().getFullYear());
        | All rights reserved | This template is made with
        i.fa.fa-heart-o aria-hidden="true"
        | by
        a href="https://colorlib.com" target="_blank"  Colorlib
      /! Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0.
      .col-lg-6.col-sm-12.footer-social
        a href="#"
          i.fa.fa-facebook
        a href="#"
          i.fa.fa-twitter
        a href="#"
          i.fa.fa-dribbble
        a href="#"
          i.fa.fa-behance

app/views/shared/_header.html.slim
.header-top
  .container
    .row
      .col-lg-6.col-sm-6.col-8.header-top-left.no-padding
        ul
          li
            a href="#"
              i.fa.fa-facebook
          li
            a href="#"
              i.fa.fa-twitter
          li
            a href="#"
              i.fa.fa-dribbble
          li
            a href="#"
              i.fa.fa-behance
      .col-lg-6.col-sm-6.col-4.header-top-right.no-padding
        a href=("tel:+953 012 3654 896")
          span.lnr.lnr-phone-handset
          span.text +953 012 3654 896
        a href="mailto:support@colorlib.com"
          span.lnr.lnr-envelope
          span.text support@colorlib.com
        - unless current_user
          a
            span.lnr
            span.text |
          = link_to  new_user_session_path
            span.lnr
            span.text Login
          = link_to  new_user_registration_path
            span.lnr
            span.text Register
        - if current_user
          a
            span.lnr.lnr-envelope
            span.text |
          = link_to  edit_user_password_path
            span.lnr
            span.text = current_user.email
          = button_to  destroy_user_session_path, method: :delete
            span.lnr
            span.text Logout
.container.main-menu
  .row.align-items-center.justify-content-between.d-flex
    #logo
      a href="/index.html"
        = image_tag "logo.png", title: "", class: ""
    nav#nav-menu-container
      ul.nav-menu
        li
          = link_to 'Home', '/'
        li
          = link_to 'About', '/about.html'
        li
          = link_to 'Courses', '/courses'
        li
          = link_to 'Events', '/events.html'
        li
          = link_to 'Gallery', '/gallery.html'
        li.menu-has-children
          = link_to 'Blog', '/'
          ul
            li
              = link_to 'Blog Home', '/blog-home.html'
            li
              = link_to 'Blog Single', '/blog-single.html'
        li.menu-has-children
          = link_to 'Pages', '/'
          ul
            li
              = link_to 'Course Details', '/course-details.html'
            li
              = link_to 'Event Details', '/event-details.html'
            li
              = link_to 'Elements', '/elements.html'
            li.menu-has-children
              = link_to 'Level 2', '/'
              ul
                li
                  = link_to 'Item One', '/'
                li
                  = link_to 'Item Two', '/'
        li
          = link_to 'Contact', 'contact'
      /! #nav-menu-container